; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:freenove]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
board_build.f_cpu = 240000000L
board_build.arduino.memory_type = qio_opi
build_flags =
    -DBOARD_HAS_PSRAM
    -O2

lib_deps =
    links2004/WebSockets@2.4.1
    olikraus/U8g2@2.36.18

monitor_speed = 115200
upload_speed = 921600

upload_port = /dev/cu.usbmodem5C930539171
monitor_port = /dev/cu.usbmodem5C930539171

monitor_dtr = 0
monitor_rts = 0
